services:
  ollama:
    container_name: ollama
    image: "ollama/ollama:latest"
    ports:
      - "11434:11434"
    volumes:
      - type: bind
        source: ollama
        target: /root/.ollama
    # environment:
    #   - OLLAMA_HOST=0.0.0.0
    #   - OLLAMA_ORIGINS=*
    